# Generated by Django 3.2.9 on 2021-12-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
                ('harga', models.IntegerField()),
                ('jml_fasilitas', models.IntegerField()),
                ('jarak', models.IntegerField()),
                ('gm_url', models.TextField()),
            ],
        ),
    ]
