# Generated by Django 3.2.9 on 2021-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisata',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
