# Generated by Django 3.2.9 on 2021-12-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0005_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='body',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='title',
        ),
        migrations.AddField(
            model_name='rule',
            name='harga',
            field=models.CharField(choices=[('murah', 'Murah'), ('sedang', 'Sedang'), ('mahal', 'Mahal')], default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='hasil',
            field=models.CharField(choices=[('rekomendasi', 'Rekomendasi'), ('tidak_rekomendasi', 'Tidak Rekomendasi')], default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='jarak',
            field=models.CharField(choices=[('jarak', 'Jarak'), ('sedang', 'Sedang'), ('jauh', 'Jauh')], default='nothing', max_length=50),
        ),
    ]
