# Generated by Django 3.2.9 on 2021-12-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0007_rule_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='fasilitas',
            field=models.CharField(choices=[('sedikit', 'Sedikit'), ('sedang', 'Sedang'), ('banyak', 'Banyak')], default='nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='nama',
            field=models.CharField(max_length=10),
        ),
    ]
